% ======================================================================= % 
% IRR second order structure SOS This function take two arguments 
% SOS & GAIN Matraix. : irrsos_coeffs_gen_for_armFun(SOS,G)
% The output is Producing a (.h file) that contains the filter coefficients
% in the [arm form array] + define to the filter gain and the number of
% sections of the generated filter ready to use in C.
% ======================================================================= %

% This function generates a C header file with filter coefficients
% from a given second-order-section (SOS) matrix and gain.
% It includes the gain in the filter coefficients and outputs a .h file.
%
% Arguments:
%   SOS  - Second-order-section matrix [num_sections x 6]
%   gain - Gain value (scalar or vector) to apply across all sections
    
function irrsos_coeffs_gen_for_armFun(SOS, gain)

    % Validate input arguments
    if isempty(SOS) || size(SOS, 2) ~= 6
        error('Invalid input matrix. SOS must have 6 columns.');
    end
    
    % if isempty(gain) || length(gain) ~= size(SOS, 1)
    %     error(['The number of gain entries must match ' ...
    %            'the number of sections in SOS.']);
    % end
    
    % Compute the total gain
    G_total = prod(gain);

    % Get the number of sections
    num_sections = size(SOS, 1);
    
    % Ask user for a file name to store the result
    fname = input(['Enter file name for coefficients' ...
                   '(please add .h after the name): '], 's');
    
    % Validate the file name
    if isempty(fname)
        error('File name is required. Please provide a valid file name.');
    end
    if ~endsWith(fname, '.h')
        fname = strcat(fname, '.h'); % Append ".h" if missing
    end
    
    % Open the file to write
    fid = fopen(fname, 'wt');
    if fid == -1
        error(['Unable to open file for writing.' ...
               'Check the file name and path.']);
    end
    
    % Write header comments
    fprintf(fid, '/**\n');
    fprintf(fid, ' * %s\n', fname);
    fprintf(fid, ' * Generated by MATLAB\n');
    fprintf(fid, ' **/\n\n');
    
    fprintf(fid, '#define FILTER_GAIN %2.8Ef\n', G_total);
    % Write: Define the number of sections
    fprintf(fid, '#define NUM_SECTIONS %d\n', num_sections);

    % Write the coefficients in the format required:
    % b0, b1, b2, -a1, -a2 for each section
    fprintf(fid, '\nconst float32_t pCoeffs[NUM_SECTIONS * 5] = { \n');
    for i = 1:num_sections
        % Apply gain to the b coefficients, keep a coefficients unchanged
        if i == num_sections
            fprintf(fid, '%2.8Ef, %2.8Ef, %2.8Ef, %2.8Ef, %2.8Ef};\n', ...
                SOS(i, 1), SOS(i, 2), SOS(i, 3), ...
                -SOS(i, 5), -SOS(i, 6));
        else
            fprintf(fid, '%2.8Ef, %2.8Ef, %2.8Ef, %2.8Ef, %2.8Ef,\n', ...
                SOS(i, 1), SOS(i, 2), SOS(i, 3), ...
                -SOS(i, 5), -SOS(i, 6));
        end
    end

    % Close the file
    fclose(fid);
    
    fprintf('C header file generated successfully: %s\n', fname);
end
